# name: Unit Tests

# on:
#   pull_request:
#   push:
#     branches: [ main ]
#   workflow_dispatch:

# jobs:
#   unit_tests:
#     runs-on: ubuntu-latest
#     timeout-minutes: 15
#     strategy:
#       matrix:
#         python-version: ['3.10']
#     steps:
#       - name: Check out repo
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - name: Setup conda env
#         uses: conda-incubator/setup-miniconda@v2
#         with:
#           auto-update-conda: true
#           miniconda-version: "latest"
#           activate-environment: test
#           python-version: '3.10'
#           auto-activate: false
#       - name: Verify conda environment
#         shell: bash -l {0}
#         run: |
#           conda info
#           which python
#           which conda
#       - name: Update pip
#         shell: bash -l {0}
#         run: python -m pip install --upgrade pip
#       - name: Install torchforge
#         run: ./scripts/install.sh
#       - name: Run unit tests with coverage
#         # TODO add all tests
#         run: pytest tests/unit_tests --cov=. --cov-report=xml --durations=20 -vv
#       - name: Upload Coverage to Codecov
#         uses: codecov/codecov-action@v3
